// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://imksrgvtulazruhdzvgb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imlta3NyZ3Z0dWxhenJ1aGR6dmdiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQ0MzI0MzQsImV4cCI6MjA5MDAwODQzNH0.GLo7DV4DKIGnZlfz2A13d4KUkHYQF5TCZzWHBa0tIKU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});